### ISSUE TITLE
Drop EC math operators?

### ISSUE THREAD

**Issue by tiran** [wbond/asn1crypto#100]
I noticed that the ``PrimePoint`` class for elliptic curve implements multiplication and addition over an elliptic curve. Internally it uses a pure Python implementation with an optional accelerator for inverse mod using CFFI and OpenSSL's big numbers. I'm rather worried about the custom implementation in asn1crypto. It doesn't seem to implement protection against malicious input, see https://safecurves.cr.yp.to/

Does asn1crypto really need to come with a custom EC math implementation? After all isn't its primary purpose ASN.1 handling and a high level interface to common ASN.1 data structures?

**Comment by joernheissler** [comment]
I agree that those operations shouldn't be part of the asn1 library.

About the security: If the operations are only used on public values, e.g. to **verify** a signature, is there any risk from malicious input?

**Comment by tiran** [comment]
The EC math is part of the public API. It can be easily used and abused to e.g. create a ECDH key share. A co-worker showed me a two liner in Python.

**Comment by wbond** [comment]
I'm fine with making it harder (impossible, if that is even possible?) to use the EC stuff. It exists so that a public key can be obtained from a private key, no more, no less. It is definitely not intended to be used for any sort of signing or verification.

How do you see it exposed through the public API right now?

IMO It was a horrible omission by whoever to make it optional to include public keys with private keys in ASN.1 form.

**Comment by wbond** [comment]
I just looked through the code, and it appears to be private and never exposed through the public API. However, I may have missed something.

**Comment by tiran** [comment]
``asn1crypto.keys`` exposes the ``PrimeCurve`` and ``PrimePoint`` class as well as ``SECP*_BASE_POINT``, which have a public ``curve`` parameter. Since ``PrimePoint`` instances implement ``__add__``, ``__mul__``, and related dunder methods, the EC math is part of the public interface.

**Comment by wbond** [comment]
So would it be considered private if they were imported with single or double underscore names instead of the non-prefixed names?

**Comment by tiran** [comment]
``PrimePoint`` instances are still user-visible. I'd consider EC math private, if the ``PrimePoint`` class would no longer implement ``__add`` and ``__mul__`` over elliptic curves. Basically I'm proposing to make the prime curve and prime point just dumb containers.

```
class PrimeCurve():
    def __init__(self, p, a, b):
        self.p = p
        self.a = a
        self.b = b


class PrimePoint():
    def __init__(self, curve, x, y, order=None):
        self.curve = curve
        self.x = x
        self.y = y
        self.order = order

def _ec_public_from_private(base_point: PrimePoint, secret: int) -> PrimePoint:
    do_ec_math_here
```

The ``PrimeCurve.contains`` should be ok, except it might be a bit slow.

**Comment by wbond** [comment]
Where are the `PrimePoint` objects visible? Perhaps if we were discussing files and line numbers this would be more clear, plus what criteria you have for "private".

**Comment by wbond** [comment]
@tiran Ping

**Comment by joernheissler** [comment]
```python3
from asn1crypto.keys import PrimePoint
```

I don't think that anyone would use an ASN.1 library to carry out private key operations. And if they do, it's their own fault.
If operations are only done on public keys, e.g. signature verification, I don't see a security risk.

Computing the public key from a private key, i.e. the reason why the ec math exists here, looks like a convenient function. But it could be attacked in this scenario:

> The victim is a webserver running an ACME client. It wants to obtain a
> certificate. First it creates a private key: `openssl genpkey …`. Next it needs
> a CSR. It uses asn1crypto to load the private key, derive the public key and
> assemble the `CertificationRequestInfo`. Asn1crypto is used here because one
> can specify the exact contents of the cri, a flexibility that's not available
> from other libs. The result is dumped to DER and signed using a secure ec
> implementation. Asn1crypto again is used to combine the signature and the cri
> into the csr. The ACME service issues the cert. And the attacker knows the
> private key.

A better implementation would use the secure ec2 implementation to load the private key and return the public key. Then use the already loaded private key to sign the request.

The public_key property can be dangerous to use. The DSA implementation uses python's pow which is probably insecure too. Only the RSA part looks secure because nothing needs to be computed.
A few other functions use public_key, so those would be insecure as well.

Providing a secure implementation doesn't appear to be feasible. In my opinion, users should be made aware of the implications of using asn1crypto to work with private keys "If unsure, don't!". Alternatively those functions could get removed completely.

**Comment by wbond** [comment]
> ```python
> from asn1crypto.keys import PrimePoint
> ```

Right, so my original proposal was to rename it to something like `__PrimePoint`, which should name mangle it and make it so it isn't accessible, right?

> The victim is a webserver running an ACME client. It wants to obtain a
certificate. First it creates a private key: openssl genpkey …. Next it needs
a CSR. It uses asn1crypto to load the private key, derive the public key and
assemble the CertificationRequestInfo. Asn1crypto is used here because one
can specify the exact contents of the cri, a flexibility that's not available
from other libs. The result is dumped to DER and signed using a secure ec
implementation. Asn1crypto again is used to combine the signature and the cri
into the csr. The ACME service issues the cert. And the attacker knows the
private key.

I don't understand what asn1crypto is doing in this scenario that is leaking the private key.

> The public_key property can be dangerous to use. The DSA implementation uses python's pow which is probably insecure too. Only the RSA part looks secure because nothing needs to be computed.
A few other functions use public_key, so those would be insecure as well.

If asn1crypto was doing general purpose cryptography, I would definitely consider it to be insecure. My understanding of timing attacks is that they function on measuring the timing of branches to determine information about the key being used. In the case of determining the public key from the private key, this is a single computation that only ever operates on a single value. Executing the same `pow()` function repeatedly won't follow different branches, so no meaningful information is revealed. If the `pow()` function was used repeatedly to sign various values, then the attacker can craft the values to be signed to reveal information about the private key. The elliptic curve computation is similar in that the exact same value is computed each time, thus not revealing any information.

If I am misunderstanding this in some way, and the existence of being able to computer the public key from the private key is a security issue, I'm happy to remove it and instead document ways that users can safely compute the value.

Perhaps one of the two of you know a cryptographer that can explain the vulnerability or confirm that the current code at https://github.com/wbond/asn1crypto/blob/5c487d88d8bf73ce9e1dce92a86041031ee0ca19/asn1crypto/keys.py#L597-L659 is not leaking information. That is to say, if we can come up with a satisfactory way to prevent users from importing `PrimePoint`.

**Comment by joernheissler** [comment]
> Right, so my original proposal was to rename it to something like `__PrimePoint`, which should name mangle it and make it so it isn't accessible, right?

It would still be accessible, but not easily. I'm not sure about @tiran's intentions. Remove the public interface or remove the code?

> I don't understand what asn1crypto is doing in this scenario that is leaking the private key.

It uses `public_key` to calculate the public key from the private key. If the implementation can be attacked through side channel attacks (and I believe it can), the private key can be reconstructed.

> Executing the same pow() function repeatedly won't follow different branches, so no meaningful information is revealed.

Basically a simple square-and-multiply algorithm works like this:

```python3
def bits(n):
    while n:
        yield n % 2
        n //= 2

def powmod(a, b, m):
    """Calculate (a ** b) % m"""
    r = 1

    for n in bits(b):
        if n:
            r = r * a % m
        a = a * a % m

    return result
```

For each bit of `b`, the inner operation is either executed (1-bit) or not (0-bit). Those are different branches. Depending on the side channel available, it might be possible to see the difference between `a = a * a % m` and `r = r * a % m`. The total time of the whole computation won't help. But power consumption over time should do the trick. And there are cpu-cache attacks which I think of as magic. They should work too. A simple improvement on above implementation would be to add an `else:` clause doing an operation on a second variable.

The ECC case is worse. For every bit you do a "double" operation. And depending on the private bits you do "plus" operations or you don't. Those are two quite different operations and probably much easier to distinguish from each other.

I'm certainly no expert on side channel attacks. I know some theory about them, but I never tried to mount one. What I do know is that they are real and that implementing crypto math is usually a bad idea, at least if private keys are involved.

Would be great if an actual expert could confirm the above or correct me. I'm not in contact with any experts.

**Comment by wiml** [comment]
I notice that [oscrypto also has a hidden ECDSA implementation](https://github.com/wbond/oscrypto/blob/master/oscrypto/_ecdsa.py) although it's based on the primitives in asn1crypto it's still a little unexpected.

What about splitting the Python ECDSA implementation out into an optional dependency? Either just moving the code into its own modularcrypto module, or using something like [Brian Warner's ecdsa module](https://github.com/warner/python-ecdsa)? Users would then be able to choose based on their compatibility / security preference — would they rather fail to load private-only PKCS8 keys, or would they rather load them but potentially leak them through a sidechannel?

(For what it's worth, although I am not an expert either, my understanding of the sidechannel issues matches joernheissler's.)

Another advantage is that if the python ECDSA module is visible, instead of an internal part of the ASN.1 module, it makes it more likely that people with an understanding of ECDSA implementation pitfalls might review it for correctness/safety.

**Comment by wbond** [comment]
This has been removed with 564e744e9b3ec01b542efcac57949a704e3de8a4 and will be part of the next release. oscrypto now has the pure-python ECDSA implementation, but it is only used for Windows XP since advapi32 lacks EC crypto support.
