### ISSUE TITLE
how i can make PKCS#7 detached signature?

### ISSUE THREAD

**Issue by best-tech** [wbond/asn1crypto#141]

**Comment by wbond** [comment]
This library is mostly low-level access to ASN.1 structures. It includes structures from a number of cryptographic standards, but doesn't implement the rules by which to construct valid structures.

Currently I've written a handful of small libraries to do such, which you can find at https://github.com/wbond/asn1crypto#related-crypto-libraries. I have not written a library for CMS construction. Partially because I have not needed it, but also because it is rather complex since CMS is used in many places.

You will most likely need to learn a bit about CMS and the needs of your project and then use the asn1crypto library to build up the structure you need.
