### ISSUE TITLE
country_name spec should be PrintableString

### ISSUE THREAD

**Issue by space88man** [wbond/asn1crypto#142]
In x509.py the _oid_spec for country_name is DirectoryString;
it seems it should be PrintableString. I verified that this is what
OpenSSL uses.

https://www.alvestrand.no/objectid/2.5.4.6.html

**Comment by wbond** [comment]
Since PrintableString is a choice of DirectoryString, we use DirectoryString since there are plenty of certificates in the wild which are technically broken since they use other encodings such as UTF8String.

In general asn1crypto follows the robustness principle / Postel's law in trying to be liberal in what we accept from others. If we didn't do this, people just wouldn't use asn1crypto since there are lots of broken certs out there, and other software works with them.

Here is the code to generate a Name, which special-cases country name to ensure it is printable:

https://github.com/wbond/asn1crypto/blob/master/asn1crypto/x509.py#L1016-L1020

**Comment by wbond** [comment]
Closing, as there doesn't seem to be any other discussion about this.
