### ISSUE TITLE
CRL version 3

### ISSUE THREAD

**Issue by vinas003** [wbond/asn1crypto#236]
RFC 5280 states that a CRL can only be version 1 or 2.
https://datatracker.ietf.org/doc/html/rfc5280#section-5.1.2.1

Asn1crypto have a version 3 as well.
https://github.com/wbond/asn1crypto/blob/master/asn1crypto/crl.py#L43

Openssl also indicate something wrong when using v3.
openssl crl -text -noout -in crl.crl
```
Certificate Revocation List (CRL):
        Version unknown (2)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = SE, ST = Stockholm, L = Stockholm, O = SUNET, OU = SUNET Infrastructure, CN = ca-test.sunet.se, emailAddress = soc@sunet.se
...
```

When using v2 all seems ok.
openssl crl -text -noout -in crl.crl
```
Certificate Revocation List (CRL):
        Version 2 (0x1)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = SE, ST = Stockholm, L = Stockholm, O = SUNET, OU = SUNET Infrastructure, CN = ca-test.sunet.se, emailAddress = soc@sunet.se
...
```

**Comment by MatthiasValvekens** [comment]
Hmm, I also can't find a reference to `v3` CRLs in the copy of Rec. ITU-T X.509 (10/2016) | ISO/IEC 9594-8:2017 sitting on my machine, and the requirement that the version be set to `v2` on CRLs is present even in X.509 (of which RFC 5280 is a profile).

Having said that, _syntactically_, the `v3` value is valid: in the X.509 ASN.1 module (Annex A of the cited document), the `version` field in both `TBSCertificate` and `CertificateListContent` refer to the same type definition for `Version`, which includes `v1`, `v2` and `v3`. For `Certificate`s, using `v3` makes sense. For `CertificateList`s, not so much, hence why there's an additional rule restricting the permissible values to `v2`.

So, personally, I'd chalk this up to a quirk in the way the X.509 spec is structured rather than a bug in `asn1crypto`, to be honest.

**Comment by mttcpr** [comment]
I agree, it's not broken.

Although there is no such thing as a v3 at this time, it is not the least
bit harmful to accept the value in a library like this. Will might prefer
to change it for aesthetics to be matchy matchy with the standard, or might
prefer to leave it as is. Either way is the same / makes no difference as
far as I'm concerned. If a person is using a lower level library that
allows you to fiddle with these values when encoding CRLs it is
incumbent on them to know what they are doing. If one doesn't know what
they are doing to this level then they should probably be using higher
level functionality that insulates them from these details.

**Comment by wbond** [comment]
Most likely it was a copy-paste of the definition of `Version` from x509.py. Originally things were tightly coupled, and then at some point I segmented them to reduce coupling and improve handling of the edge cases. I believe this was during my initial development of the library, before I started tracking all code changes as commits in git.

**Comment by vinas003** [comment]
@wbond Would you support a pull request to remove version 3?

**Comment by wbond** [comment]
@vinas003 Yes

**Comment by vinas003** [comment]
Seems the tests failed because of https://github.com/wbond/crlbuilder

So I made a pull request for that repo as well.
Hope I changed v3 -> v2 in all places.
