### ISSUE TITLE
Can asn1crypto support pickle!

### ISSUE THREAD

**Issue by gudder** [wbond/asn1crypto#239]
Whether asn1crypto supports serialization and deserialization with files. I found that it could not work normally after being serialized and saved to a file. It was not in the same memory twice.
[https://github.com/MatthiasValvekens/pyHanko/discussions/154](interrupted_signing)

**Comment by MatthiasValvekens** [comment]
To provide some extra context here, since I own the repo where that discussion happened:

The issue is not so much in pickling `asn1crypto` objects themselves (because as we all know, serialisation/deserialisation of ASN.1 objects is pretty much the whole point of this library), but in figuring out the cleanest way to use `pickle` on objects that _contain_ instances from `asn1crypto`, possibly deeply nested within their state. At the moment, pickling and unpickling such objects doesn't work reliably because `asn1crypto` relies on some class-level setup logic that doesn't play nice with the way unpickling populates object state.

The main question, as I see it, is whether or not anything needs to change in `asn1crypto` to support this use case. In other words, _if_  it's possible to make `pickle` rely on `asn1crypto`'s own `dump()` and `load(...)` API without making changes in `asn1crypto`, then there's obviously no need for `asn1crypto` to do anything. Alternatively, it might be possible to include a generic `__reduce__` implementation in `Asn1Value`, but that solution doesn't sound as appealing to me because it'd probably be a pain to get it to work across all Python versions that `asn1crypto` supports.

Now, while I'm not terribly familiar with the way `pickle` works, and I haven't investigated this issue further yet, [the `copyreg` API looks like a promising candidate](https://docs.python.org/3/library/copyreg.html) to solve this problem without touching any `asn1crypto` code.

@gudder, is that something you could work with?

**Comment by MatthiasValvekens** [comment]
OK, I figured out a way to make this work without making changes in asn1crypto, but the workaround requires a piece of Python 3.8+ API.

First off, the `copyreg` approach doesn't work because the dispatch table doesn't take into account subclasses, so you'd have to register a custom reduction function for every subclass of `Asn1Value`, and that's not really doable.

However, starting in Python 3.8, you can subclass `Pickler` and do the following:


```python
from asn1crypto import core


# NOTE: this function _must_ be a top-level function in an importable module!

def _reconstruct_asn1value(asn1crypto_cls: Type[core.Asn1Value], der_bytes: bytes):
     return asn1crypto_cls.load(der_bytes)


class CustomPickler(pickle.Pickler):
    def reducer_override(self, obj):
        if isinstance(obj, core.Asn1Value):
            return _reconstruct_asn1value, (obj.__class__, obj.dump())
        else:
            return NotImplemented   # fallback to default processing

obj = ....    # something involving asn1crypto objects 

with open('/tmp/blah.bin', 'wb') as outf:
    pickler = CustomPickler(outf)
    pickler.dump(obj)
```

You can then simply load `/tmp/blah.bin` using `pickle.load(...)`, no custom logic needed.


Here's what's going on: this will force `pickle` to deserialise all `Asn1Value` objects (including subclasses) as a `(<class>, <DER encoding>)` tuple. The class will be automagically imported from `asn1crypto` at load time (it's serialised as a reference), and `obj.dump()` just returns bytes, so of course deserialising those is not a problem either. When unpickling, the class and the DER bytes are then passed to `_reconstruct_asn1value` (which must be importable, remember!), and that function calls `asn1crypto`'s own `load()` function in the usual way.

Pros:

 - This approach also works on `asn1crypto` objects nested in other objects.
 - It's actually a lot more efficient than `pickle`'s default serialisation of `asn1crypto` values, mainly because it doesn't need to care about caching-related things.
 - This approach doesn't touch any global state or require any modifications to `asn1crypto`.

Cons:
 - `reducer_override` doesn't work on Python versions below 3.8
 - It requires a custom `Pickler` subclass, so if you already have other `pickle` hooks in your code, you might need to mess around a little to get them to behave.

It would be nice if `Asn1Value` would implement `__reduce__` using `dump()`/`load()`, though. Then the workaround wouldn't be necessary in the first place.

**Comment by gudder** [comment]
It can work with pickle, which makes it more convenient to use. Thank you for your help！
