### ISSUE TITLE
ValueError: Hash algorithm not known for rsassa_pkcs1v15

### ISSUE THREAD

**Issue by ThomasReifferscheid** [wbond/asn1crypto#263]
I'm getting "ValueError: Hash algorithm not known for rsassa_pkcs1v15" on asn1crypto 1.5.1 from venv\lib\site-packages\asn1crypto\algos.py", line 390, in hash_algo when doing:

```
from certvalidator import CertificateValidator

with open('full_chain_in_pem_x509_format.pem', 'rb') as f:
    end_entity_cert = f.read()

validator = CertificateValidator(end_entity_cert)
validator.validate_usage(set(['digital_signature']))

```

When calling openssl I get:

```
openssl x509 -in full_chain_in_pem_x509_format.pem -noout -text | grep -i rsa
        Signature Algorithm: sha384WithRSAEncryption
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
    Signature Algorithm: sha384WithRSAEncryption

```

Please assist - Thank you.
Thomas

**Comment by MatthiasValvekens** [comment]
This is almost certainly not a bug in asn1crypto, but it could point to an issue in certvalidator (maybe), or more likely an issue with one of the certificates in your file.

Hard to tell exactly what the problem is without seeing the cert, but I guess it's something like this: using `rsassa_pkcs1v15` as a signature algorithm identifier requires the digest algorithm to be defined elsewhere. This is straightforward in some contexts (e.g. CMS), but it kinda doesn't make a whole lot of sense in an X.509 cert (IIRC the generic `rsassa_pkcs1v15` OID is banned in PKIX and many other common X.509 profiles). Perhaps openssl implements some kind of fallback here.

**Comment by ThomasReifferscheid** [comment]
After removing the private key from the pem file the error was gone. Sorry for the noise.
Thomas

**Comment by MatthiasValvekens** [comment]
Ah, that also makes sense (RSA reuses that OID for keys as well, so that's where asn1crypto might've wound up confused).
