### ISSUE TITLE
Indefinite length encoding supported on input?

### ISSUE THREAD

**Issue by aalba6675** [wbond/asn1crypto#36]
v0.21.1

Encountered a p12 file using indefinite length encoding in auth_safe. The Content-Info OctetString is not aggregated correctly from the substrings. The reconstructed OctetString is too large and the native value contains the ASN.1 headers of the substrings instead of only content.

Test case

Input string in hex = '2480040d8dfff0980736af936e423acfcc04159277f7f0e479ffc7dc33b2d03d7b1a186d4472aa490000'

[dummy.zip](https://github.com/wbond/asn1crypto/files/812869/dummy.zip)

$ openssl asn1parse -inform DER -in dummy.da2
    0:d=0  hl=2 l=inf  cons: OCTET STRING      
    2:d=1  hl=2 l=  13 prim: OCTET STRING      [HEX DUMP]:8DFFF0980736AF936E423ACFCC
   17:d=1  hl=2 l=  21 prim: OCTET STRING      [HEX DUMP]:9277F7F0E479FFC7DC33B2D03D7B1A186D4472AA49
   40:d=1  hl=2 l=   0 prim: EOC               

Expected behaviour: an OctetString whose native value is a byte string of length 34 
```python
>>> data = binascii.unhexlify('2480040d8dfff0980736af936e423acfcc04159277f7f0e479ffc7dc33b2d03d7b1a186d4472aa490000')
>>> x = core.OctetString.load(data)
>>> len(x.native)
34
>>> binascii.hexlify(x.native)
b'8dfff0980736af936e423acfcc9277f7f0e479ffc7dc33b2d03d7b1a186d4472aa49'
```

Observed behaviour:
```python
>>> data = binascii.unhexlify('2480040d8dfff0980736af936e423acfcc04159277f7f0e479ffc7dc33b2d03d7b1a186d4472aa490000')
>>> x = core.OctetString.load(data)
>>> len(x.native)
38
>>> binascii.hexlify(x.native)
b'040d8dfff0980736af936e423acfcc04159277f7f0e479ffc7dc33b2d03d7b1a186d4472aa49'

## note ASN.1 headers 040d and 0415 are in the native value
```

**Comment by joernheissler** [comment]
ValueError: Error parsing asn1crypto.core.OctetString - method should have been primitive, but constructed was found

That's what I get.

**Comment by aalba6675** [comment]
@joernheissler  what version are you using?
$ python --version
Python 3.5.2
$ pip show asn1crypto
Name: asn1crypto
Version: 0.21.1

**Comment by aalba6675** [comment]
The following test fix only works for OctetString and forces tag 0 (implicit tag 0 in EncryptedContentInfo) to tag 4. This is a POC for the p12 file I hit in the wild with indefinite length encoding all over the place. Just for discussion...i

```python
#
#diff --git a/asn1crypto/core.py b/asn1crypto/core.py
#index f7487f4..ed7c2bf 100644
#--- a/asn1crypto/core.py
#+++ b/asn1crypto/core.py
@@ -4773,6 +4773,16 @@ def _build(class_, method, tag, header, contents, trailer, spec=None, spec_param
                         METHOD_NUM_TO_NAME_MAP.get(value.method),
                         METHOD_NUM_TO_NAME_MAP.get(method, method)
                     ))
+                else:
+                    tag = 4
+                    new_contents = b''
+                    contents_len = len(contents)
+                    offset = 0
+                    while offset < contents_len:
+                        item, offset  = _parse(contents, contents_len, offset)
+                        new_contents += item[4]
+                    value = spec(contents=new_contents)

```

**Comment by wbond** [comment]
(See http://luca.ntop.org/Teaching/Appunti/asn1.html, Section 3 for info on the header values discussed below).

The first byte is `\x24`, which is `b00100100`. The 6th bit being `1` indicates it is constructed, with the remainder of the byte representing `\x04`, the tag for OctetString.

The second byte is `\x80`, which indicates the length is indefinite, and the string should be scanned, stopping at the first `\x00\x00` that is not part of a child record.

Thus, the value of this OctetString is everything after `\x80` and before the trailing `\x00\x00`. Thus, asn1crypto is returning the correct result for `binascii.hexlify(x.native)`.

The `openssl asn1parse` command is *further* parsing the contents of the OctetString. To accomplish this with asn1crypto, you'd need to use `core.ParsableOctetString` instead of `core.OctetString`. You can then try accessing the `.parsed` attribute to see if the contents are a valid DER/BER encoded value.

However, the contents of the outer constructed OctetString are not just a single ASN.1 value, but rather a concatenation of number of values together. I don't know that I have ever seen this in a spec, except when someone is trying to create backwards compatibility with an existing ASN.1 spec, but they want to add optional data to the end. The only instance of know of this is the `TRUSTED CERTIFICATE` encoding that OpenSSL uses to append trust information after a PEM-encoded X.509 certificate.

To handle this situation, you kind of need to know it is going to exist. I wonder if there is part of the PKCS#12 spec I missed that uses this, or if it is some legacy variation of the encoding? It is almost identical to the issue in #24. There a CMS structure had an indefinite length segment that was a concatenation of a number of smaller chunks of data. These can't be DER values since they use indefinite length, but it would be nice to know if the file is an anomaly, or something asn1crypto needs to handle.

The code below should be a proper handling of this construct using asn1crypto 0.21.1 or newer:

```python
# coding: utf-8
from __future__ import unicode_literals, division, absolute_import, print_function

from asn1crypto import core, parser
import binascii

data = binascii.unhexlify(b'2480040d8dfff0980736af936e423acfcc04159277f7f0e479ffc7dc33b2d03d7b1a186d4472aa490000')
payload = core.OctetString.load(data).native
print(len(payload))

values = []
while len(payload) > 0:
    info = parser.parse(payload)
    sub_len = len(info[3]) + len(info[4]) + len(info[5])
    values.append(core.load(payload[:sub_len]))
    print(values[-1])
    payload = payload[sub_len:]

```

**Comment by joernheissler** [comment]
@aalba6675 forget it. I was being stupid.

**Comment by wbond** [comment]
@aalba6675 You don't happen to have any .p12 files that exhibit this behavior that you could share with me, do you?

**Comment by joernheissler** [comment]
To me, https://www.itu.int/ITU-T/studygroups/com17/languages/X.690-0207.pdf is the authoritative specification.

Chapter 8.7 is called "Encoding of an octetstring value" and it goes further on:

    8.7.3.1 To encode an octetstring value in this way, it is segmented.
    Each segment shall consist of a series of consecutive octets of the value.
    There shall be no significance placed on the segment boundaries."

My understanding is that a constructed OctetString still represents a single OctetString value. Imho asn1crypto should return the value as whole,  i.e. without the internal structure, when using OctetString.native or bytes(OctetString).

**Comment by wbond** [comment]
Ok, that makes sense – and it more logical than my understand of how indefinite length was used before. Since the encoder doesn't know how long the value is ahead of time, it effectively provides chunks of OctetString values until it no longer has any.

From looking over the X.690 spec, it seems to mention the constructed encoding as applied to BitString, OctetString and "restricted character strings". So asn1crypto should seamlessly handle parsing those values and returning them from `.native`.

**Comment by aalba6675** [comment]
It is generated by EJBCA (which software loves to do "streaming" type of CMS with indefinite encodings). The p12 passphrase is "EJBCA_ADMIN_PASS"

[indefinite.zip](https://github.com/wbond/asn1crypto/files/813510/indefinite.zip)

**Comment by aalba6675** [comment]
When using pyasn1, it reconstructs  OctetString as @joernheissler suggested with no internal structure: i.e. grab all the OctetString chunks, concat their .native, and return a new OctetString

**Comment by joernheissler** [comment]
[testcase.py.txt](https://github.com/wbond/asn1crypto/files/813889/testcase.py.txt)

**Comment by wbond** [comment]
This should be resolved by f577cfff05e37b4baf4820973400730868155477 and 04c7ea7657e57f54604b68e2ca497781819c7fc7

**Comment by aalba6675** [comment]
Thanks  - so for constructable types bytes(x) and x.native are intended to return different things, correct?

bytes(x) is the with all the chunks and
x.native is the merge contents

**Comment by wbond** [comment]
@aalba6675 That is a good point.

abf76d16c70f69c38cb3bd44d92096a2d8fa89ea should address this issue, and prevents objects from re-parsing constructed contents by caching the merged chunks.

**Comment by wbond** [comment]
I believe this is all set now.
