### ISSUE TITLE
Trouble parsing OCSP request from StrongSwan

### ISSUE THREAD

**Issue by laurivosandi** [wbond/asn1crypto#56]
Hi,

I am having trouble parsing OCSP request from StrongSwan. Base64 encoding of the DER request in question is:

```
MIGVMIGSMFEwTzBNMAkGBSsOAwIaBQAEFBD07/WvCa6V3cvOq9pdq278smVFBBSfIwRKCe7nPWojuAb164jF62AHcAIUTbNhvLwhJrngY6sYzQTi2dSkHMeiPTA7MB0GCSsGAQUFBzABAgQQhaRGOT27I73QpRF4j8XuUjAaBgkrBgEFBQcwAQQEDTALBgkrBgEFBQcwAQE= 
```
Attempting to parse extensions or run .native on the whole thing results in:

```
ValueError: Insufficient data - 1424303782342441662876496716754552 bytes requested but only 16 available
    while parsing asn1crypto.core.ParsableOctetString
    while parsing asn1crypto.ocsp.TBSRequestExtension
    while parsing asn1crypto.ocsp.TBSRequestExtensions
    while parsing asn1crypto.ocsp.TBSRequest
    while parsing asn1crypto.ocsp.OCSPRequest
```

Skipping extensions or not using .native on the whole thing works as expected.

**Comment by joernheissler** [comment]
I believe your Request is incorrectly coded.

From dumpasn1:
```
 93  29: . . . . SEQUENCE {
 95   9: . . . . . OBJECT IDENTIFIER ocspNonce (1 3 6 1 5 5 7 48 1 2)
106  16: . . . . . OCTET STRING 85 A4 46 39 3D BB 23 BD D0 A5 11 78 8F C5 EE 52
       : . . . . . }
```

The extension value is an OctetString with 16 bytes, your nonce.
According to the ASN.1 specs, however, the extension value shall be an OctetString, encapsulating another OctetString (i.e. your nonce). Details in rfc5280 (defines Extension(s)) and rfc6960 (defines the contents of your nonce extension).

Still, the error message from asn1crypto is very confusing.

Here is an OCSP request generated with openssl which asn1crypto can load+decode.
```
MHYwdDBNMEswSTAJBgUrDgMCGgUABBTPJvUY+sl+j4yzQuAcL2oQno5fCgQUUWj/kK8CB3U8zNll
ZGKiErhZcjsCEAWpXA00qDHzf4pfcpzCPHSiIzAhMB8GCSsGAQUFBzABAgQSBBADXJ0vquazfUDp
n4nEULak
```

**Comment by wbond** [comment]
The reason you are getting the error you are getting is that the header bytes of ASN.1 include tag/method/class info, plus the length of the encoded data. If the first byte in the length section has a high bit of 1, then the rest of the bits in that byte indicate how many more of the bytes are being used to encode the header. It appears since this encoding isn't properly wrapped, it is interpreting the raw data ASN.1 header info, and those bytes indicate there should be a LOT of bytes used for the rest of the value.

I suppose the only way to get around this would be to encode some upper-limit on the sane number of bytes in an encoded value. That, or bail out if the requested number of bytes is at least 100x the number available. That would preserve error conditions where some data was slightly truncated, or encoded improperly, but would catch these mistakes also.

**Comment by wbond** [comment]
@laurivosandi Did you ever make any progress with this?

**Comment by laurivosandi** [comment]
Hi, they confirmed and fixed the bug https://git.strongswan.org/?p=strongswan.git;a=commitdiff;h=d7dc677e

**Comment by wbond** [comment]
Ok, thanks for letting me know!
